# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-29 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20190429_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='adress_type',
            new_name='address_type',
        ),
    ]
