# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0011_remove_address_address_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_2',
            new_name='additional_line',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='nickname',
        ),
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='post_office',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
