# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-27 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0012_auto_20191125_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='billing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='billing.BillingProfile'),
        ),
    ]
