# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-09 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0013_auto_20191127_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
