# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-26 09:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0015_auto_20191226_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ][а-яА-Я ]+$', 'Only letters and spaces are allowed in the Location Name.'), django.core.validators.MinLengthValidator(6)]),
        ),
    ]
