# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-11 15:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0023_auto_20200415_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен начинается с "+380…"', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
