# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-08 16:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20191208_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='exp_month',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_year',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
