# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-08 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20191208_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='exp_month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='exp_year',
            new_name='year',
        ),
    ]
