# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-08 17:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_auto_20191208_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator('^\\d+$')]),
        ),
    ]
