# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_card_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
