# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-04 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_auto_20200218_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
