# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-05 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_billingprofile_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('users', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='billingprofile',
            name='rating',
        ),
    ]
