# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-05 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_auto_20200305_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='billing.Rating'),
        ),
    ]
