# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-05 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_billingprofile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
