# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-05 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='from_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='to_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='billing.BillingProfile'),
        ),
    ]
