# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-05 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_auto_20200305_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
