# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-07 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_auto_20200305_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
