# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-04-13 13:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_auto_20200413_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\d+$')]),
        ),
    ]
