# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-02 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0004_auto_20190807_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='timezone',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
