# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-02 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0005_usersession_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='timezone',
        ),
    ]
