# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-15 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ecommerce', '0002_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_chat',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_read',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_user',
            new_name='user',
        ),
    ]
