# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-14 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ecommerce', '0005_thread_buy_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='buy_requested',
        ),
    ]
