# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-03 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
