# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-06 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190506_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
