# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-07 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190505_1438'),
        ('accounts', '0018_auto_20190506_1425'),
    ]

    operations = [
    ]
