# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-09 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_user'),
        ('accounts', '0026_auto_20190509_0601'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wish',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='wish',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='item',
        ),
        migrations.AddField(
            model_name='user',
            name='wishes',
            field=models.ManyToManyField(related_name='wishes', to='products.Product'),
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
