# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-11 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20190509_1443'),
        ('accounts', '0027_auto_20190510_0755'),
    ]

    operations = [
    ]
