# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-12 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190512_0638'),
        ('accounts', '0029_merge_20190511_1233'),
    ]

    operations = [
    ]
