# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-13 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20190508_0849'),
        ('accounts', '0031_auto_20190512_0643'),
    ]

    operations = [
    ]
