# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-14 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20190512_0643'),
        ('accounts', '0030_merge_20190512_1921'),
    ]

    operations = [
    ]
