# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-15 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_merge_20190514_2316'),
        ('accounts', '0032_merge_20190513_1819'),
    ]

    operations = [
    ]
