# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-15 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_merge_20190515_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wishes',
            field=models.ManyToManyField(blank=True, related_name='users', to='products.Product'),
        ),
    ]
