# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-15 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_merge_20190515_1631'),
        ('accounts', '0033_merge_20190515_1627'),
    ]

    operations = [
    ]
