# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-16 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20190515_1648'),
        ('accounts', '0034_merge_20190515_1636'),
    ]

    operations = [
    ]
