# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-22 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_merge_20190522_1105'),
        ('accounts', '0035_merge_20190516_1954'),
    ]

    operations = [
    ]
