# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-24 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20190517_1201'),
        ('accounts', '0036_merge_20190522_1111'),
    ]

    operations = [
    ]
