# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-28 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_merge_20190524_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social',
            field=models.BooleanField(default=False),
        ),
    ]
