# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-18 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20190528_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'RU'), ('ua', 'UA'), ('en', 'EN')], default='en', max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
