# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-18 10:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_languagepreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagepreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to=settings.AUTH_USER_MODEL),
        ),
    ]
