# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-19 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20190619_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagepreference',
            name='language',
            field=models.CharField(choices=[('ru', 'RU'), ('ua', 'UA'), ('en', 'EN')], default='en', max_length=120),
        ),
    ]
