# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-07 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20190619_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=120, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=120, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
