# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-07 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20190807_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.AddField(
            model_name='regionpreference',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='region', to=settings.AUTH_USER_MODEL),
        ),
    ]
