# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-07 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analitics', '0003_regionpreference'),
        ('accounts', '0049_auto_20190807_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionpreference',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_reg', to='analitics.RegionPreference'),
        ),
        migrations.DeleteModel(
            name='RegionPreference',
        ),
    ]
