# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-07 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20190807_1738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegionPreference',
            new_name='Region',
        ),
    ]
