# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-27 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20190807_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_region', to='accounts.Region'),
        ),
    ]
