# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-06 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20190906_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='currency_mult',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, null=True),
        ),
    ]
