# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-04-06 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_region_region_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestEmail',
        ),
    ]
