# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-08 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bottoms',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='footwear',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='outwear',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tops',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
