# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-11 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='category',
            name='bottoms',
        ),
        migrations.RemoveField(
            model_name='category',
            name='footwear',
        ),
        migrations.RemoveField(
            model_name='category',
            name='outwear',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tops',
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Bottoms',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Footwear',
        ),
        migrations.DeleteModel(
            name='Outwear',
        ),
        migrations.DeleteModel(
            name='Tops',
        ),
    ]
