# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-08 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20190508_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='category',
            name='bottoms',
        ),
        migrations.RemoveField(
            model_name='category',
            name='footwear',
        ),
        migrations.RemoveField(
            model_name='category',
            name='outwear',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tops',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Bottoms',
        ),
        migrations.DeleteModel(
            name='Footwear',
        ),
        migrations.DeleteModel(
            name='Outwear',
        ),
        migrations.DeleteModel(
            name='Tops',
        ),
    ]
