# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-13 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size_pants',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_shoes',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_tops',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
