# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-09 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190509_1251'),
        ('categories', '0003_auto_20190508_1629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
