# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-13 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20190513_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size_pants',
            field=models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman'), ('unisex', 'Unisex')], max_length=120),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_shoes',
            field=models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman'), ('unisex', 'Unisex')], max_length=120),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_tops',
            field=models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman'), ('unisex', 'Unisex')], max_length=120),
        ),
    ]
