# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-13 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20190513_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_testing', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='size',
            name='size_pants',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_shoes',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_tops',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='size',
            name='size_test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.TestSize'),
        ),
    ]
