# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-13 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20190513_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='size_test',
        ),
    ]
