# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-18 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories_eng', models.CharField(blank=True, max_length=120)),
                ('accessories_ru', models.CharField(blank=True, max_length=120)),
                ('accessories_ua', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Bottoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottoms_eng', models.CharField(blank=True, max_length=120)),
                ('bottoms_ru', models.CharField(blank=True, max_length=120)),
                ('bottoms_ua', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footwear_eng', models.CharField(blank=True, max_length=120)),
                ('footwear_ru', models.CharField(blank=True, max_length=120)),
                ('footwear_ua', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_eng', models.CharField(blank=True, max_length=120)),
                ('men_ru', models.CharField(blank=True, max_length=120)),
                ('men_ua', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Outwear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outwear_eng', models.CharField(blank=True, max_length=120)),
                ('outwear_ru', models.CharField(blank=True, max_length=120)),
                ('outwear_ua', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Tops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tops_eng', models.CharField(blank=True, max_length=120)),
                ('tops_ru', models.CharField(blank=True, max_length=120)),
                ('tops_ua', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Unisex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unisex_eng', models.CharField(blank=True, max_length=120)),
                ('unisex_ru', models.CharField(blank=True, max_length=120)),
                ('unisex_ua', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woman_eng', models.CharField(blank=True, max_length=120)),
                ('woman_ru', models.CharField(blank=True, max_length=120)),
                ('woman_ua', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
