# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-18 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_accessories_bottoms_footwear_men_outwear_tops_unisex_woman'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Bottoms',
        ),
        migrations.DeleteModel(
            name='Footwear',
        ),
        migrations.DeleteModel(
            name='Men',
        ),
        migrations.DeleteModel(
            name='Outwear',
        ),
        migrations.DeleteModel(
            name='Tops',
        ),
        migrations.DeleteModel(
            name='Unisex',
        ),
        migrations.DeleteModel(
            name='Woman',
        ),
    ]
