# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-20 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_auto_20190618_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=120)),
                ('gender_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Overcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('undercategory', models.CharField(blank=True, max_length=120)),
                ('undercategory_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Undercategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('undercategory', models.CharField(blank=True, max_length=120)),
                ('undercategory_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Size')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='category_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Undercategory'),
        ),
    ]
