# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-20 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_auto_20190720_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overcategory',
            name='overcategory_for',
        ),
    ]
