# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-20 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_auto_20190720_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_admin',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='gender',
            name='gender_admin',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='size',
            name='size_admin',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='undercategory',
            name='undercategory_admin',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
