# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-20 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_auto_20190720_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Undercategory'),
        ),
    ]
