# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-26 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0017_auto_20190720_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size_for',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
