# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-30 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0019_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_eng',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='category',
            name='category_ru',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='category',
            name='category_ua',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='condition',
            name='condition_eng',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='gender',
            name='gender_eng',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='gender',
            name='gender_ru',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='gender',
            name='gender_ua',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='overcategory',
            name='overcategory_eng',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='overcategory',
            name='overcategory_ru',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='overcategory',
            name='overcategory_ua',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='undercategory',
            name='undercategory_eng',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='undercategory',
            name='undercategory_ru',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='undercategory',
            name='undercategory_ua',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
