# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-06 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0020_auto_20190730_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size_kids',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
