# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-10 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0021_size_size_kids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='undercategory',
            old_name='undercategory_ua',
            new_name='undercategory_u',
        ),
    ]
