# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-04-06 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0026_size_size_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterUrlShortener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField()),
                ('shorted_slug', models.SlugField(blank=True, default=None, unique=True)),
            ],
        ),
    ]
