# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-04-11 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0027_filterurlshortener'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterurlshortener',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
