# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-12 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='user_telegram',
            old_name='user_id',
            new_name='chat_id',
        ),
        migrations.AddField(
            model_name='user_telegram',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answermode',
            name='user_telegram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.User_telegram'),
        ),
    ]
