# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200512_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='answermode',
            name='user_telegram',
        ),
        migrations.AddField(
            model_name='user_telegram',
            name='in_answer_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AnswerMode',
        ),
        migrations.AddField(
            model_name='loginmode',
            name='user_telegram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.User_telegram'),
        ),
    ]
