# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-12 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200512_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmode',
            name='user_telegram',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.User_telegram'),
        ),
    ]
