# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-12 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20200512_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmode',
            name='user_telegram',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_mode', to='bot.User_telegram'),
        ),
        migrations.AlterField(
            model_name='user_telegram',
            name='chat_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
