# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-14 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20200512_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
