# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-14 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_paymode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymode',
            name='user_telegram',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_mode', to='bot.User_telegram'),
        ),
    ]
