# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-15 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_paymode_user_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_telegram',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_telegram', to=settings.AUTH_USER_MODEL),
        ),
    ]
