# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-04 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20200604_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('key', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expires', models.IntegerField(default=5)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
