# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-04 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_authenticationactivation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthenticationActivation',
            new_name='TelegramActivation',
        ),
    ]
