# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-05 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20200604_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramactivation',
            name='user_telegram',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_activation', to='bot.User_telegram'),
        ),
    ]
