# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-05 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_telegramactivation_user_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramactivation',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
