# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-25 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_telegramactivation_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelProductMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=200, unique=True)),
                ('product_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
