# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-25 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_channelproductmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelproductmessage',
            name='channel',
        ),
    ]
