# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-25 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_remove_channelproductmessage_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelproductmessage',
            name='message_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
