# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_channelproductmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelproductmessage',
            name='chat_id',
            field=models.CharField(max_length=200),
        ),
    ]
