# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-22 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_ecommerce', '0004_auto_20190516_1954'),
        ('test_ecommerce', '0004_auto_20190522_1106'),
    ]

    operations = [
    ]
