# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-17 08:14
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ecommerce', '0012_auto_20190613_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='input_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(location='//envision-ecommerce-1.s3.amazonaws.com/media/'), upload_to='example'),
        ),
        migrations.AlterField(
            model_name='examplefile',
            name='input_file',
            field=models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(location='//envision-ecommerce-1.s3.amazonaws.com/media/'), upload_to='example'),
        ),
    ]
