# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-19 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_ecommerce', '0014_auto_20190618_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.RemoveField(
            model_name='examplefile',
            name='example',
        ),
        migrations.DeleteModel(
            name='Example2',
        ),
        migrations.DeleteModel(
            name='ExampleFile',
        ),
    ]
