# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-13 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import image_uploader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.FileField(max_length=255, upload_to=image_uploader.models.upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_id', models.CharField(max_length=40)),
                ('form_id', models.CharField(max_length=40)),
            ],
        ),
    ]
