# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-14 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import image_uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='form_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=image_uploader.models.upload_to),
        ),
    ]
