# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-28 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import image_uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0002_auto_20190614_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='thumbnail',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=image_uploader.models.upload_to_thumb),
        ),
    ]
