# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-28 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0003_uploadedfile_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='original_filename',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='rotated_times',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
