# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-02 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0004_auto_20190628_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='rotated_times',
        ),
    ]
