# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-02 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0005_remove_uploadedfile_rotated_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='folder_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
