# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-02 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0006_uploadedfile_folder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='form_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='formId', to='image_uploader.FormId'),
        ),
    ]
