# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-02 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0007_auto_20190702_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='folder_name',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='form_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='FormId',
        ),
    ]
