# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-18 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0008_auto_20190702_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='thumbnail',
        ),
    ]
