# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-31 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_private_chat', '0002_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
