# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-18 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_file_form', '0004_auto_20170423_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='order_nr',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20),
        ),
    ]
