# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-27 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_file_form', '0005_uploadedfile_order_nr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='order_nr',
        ),
    ]
