# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-20 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('orders', '0004_auto_20190320_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_adress',
            new_name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_adress',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='addresses.Address'),
        ),
    ]
