# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-01 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ecommerce', '0004_auto_20191031_1515'),
        ('products', '0061_auto_20190906_1343'),
        ('orders', '0007_auto_20190429_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_ecommerce.Thread'),
        ),
    ]
