# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-14 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ecommerce', '0006_remove_thread_buy_requested'),
        ('orders', '0009_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_ecommerce.Thread'),
        ),
    ]
