# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-20 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_transaction_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='chat_ecommerce.Thread'),
        ),
    ]
