# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-16 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20191120_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_thread', to='chat_ecommerce.Thread'),
        ),
    ]
