# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-24 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20191216_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='thread',
        ),
        migrations.AddField(
            model_name='transaction',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
