# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-02-13 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_transaction_data_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address_final',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address_final',
        ),
        migrations.RemoveField(
            model_name='order',
            name='thread',
        ),
        migrations.AddField(
            model_name='order',
            name='track_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='created', max_length=120),
        ),
    ]
