# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-12 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190511_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path),
        ),
    ]
