# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-09 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('accessories', 'Accessories'), ('outwear', 'Outwear'), ('footwear', 'Footwear')], default='all', max_length=120),
        ),
    ]
