# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-13 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_size'),
        ('products', '0013_auto_20190511_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('accessories', 'Accessories'), ('outwear', 'Outwear'), ('footwear', 'Footwear'), ('big', 'Big')], default='all', max_length=120),
        ),
    ]
