# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-09 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190509_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman')], default='not picked', max_length=120),
        ),
    ]
