# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-15 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20190514_1034'),
        ('products', '0015_remove_product_photos'),
    ]

    operations = [
    ]
