# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-17 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_image_image_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(default=None, null=True),
        ),
    ]
