# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_imageorderutil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageorderutil',
            name='order_sequence',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
