# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-17 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20190527_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
    ]
