# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-24 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20190624_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('unisex', 'Unisex')], default='not picked', max_length=120),
        ),
    ]
