# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-24 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20190624_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman')], default='not picked', max_length=120),
        ),
    ]
