# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-27 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20190625_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='products.Product')),
            ],
        ),
    ]
