# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-12 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('item condition', 'Item condition'), ('new', 'New'), ('mint condition', 'Mint condition'), ('worn a bit', 'Worn a bit'), ('very worn', 'Very worn')], default='not picked', max_length=120, null=True),
        ),
    ]
