# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-21 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_auto_20190720_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='undercategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Undercategory'),
        ),
    ]
