# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-28 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_auto_20190721_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Condition'),
        ),
    ]
