# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-02 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_auto_20190723_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='authentic',
            field=models.CharField(choices=[('fake', 'Fake'), ('authentic', 'Authentic')], default='Undefined', max_length=120, null=True),
        ),
    ]
