# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-23 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_auto_20190805_0903'),
        ('products', '0049_auto_20190728_1720'),
    ]

    operations = [
    ]
