# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-06 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_merge_20190823_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
