# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-16 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_auto_20190906_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natinional_shipping', models.DecimalField(decimal_places=6, default=23, max_digits=16)),
                ('internatinional_shipping', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Shipping_price'),
        ),
    ]
