# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-16 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_auto_20191216_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping_price',
            old_name='internatinional_shipping',
            new_name='international_shipping',
        ),
        migrations.RenameField(
            model_name='shipping_price',
            old_name='natinional_shipping',
            new_name='national_shipping',
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_price',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.Shipping_price'),
        ),
    ]
