# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-16 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_auto_20191216_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_price',
        ),
        migrations.AddField(
            model_name='shipping_price',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
