# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-02-24 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_auto_20191216_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_price',
            name='national_shipping',
            field=models.DecimalField(decimal_places=6, default=55, max_digits=16),
        ),
    ]
