# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_auto_20200304_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='international_shipping',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='national_shipping',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16, null=True),
        ),
    ]
