# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-08 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0070_auto_20200304_1450'),
        ('products', '0070_auto_20200307_2110'),
    ]

    operations = [
    ]
