# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-08 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_merge_20200308_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency_original',
            field=models.CharField(blank=True, default='undefined', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_original',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=16, null=True),
        ),
    ]
