# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-11 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_auto_20200308_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='national_shipping',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=16, null=True),
        ),
    ]
