# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-03-22 17:50
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_auto_20200311_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productthumbnail',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=products.models.upload_image_path),
        ),
    ]
